openapi: 3.1.0
info:
  title: URL Shortener Service
  version: 1.0.1
paths:
  /create:
    post:
      summary: Create a short URL
      description: Creates a short URL for a given long URL.
      parameters:
        - in: query
          name: url
          required: true
          description: The long URL to be shortened.
          schema:
            type: string
            format: uri
      responses:
        200:
          description: Short URL created successfully
          content:
            text/plain:
              schema:
                type: string
                example: "Short URL: https://me.li/short"
        400:
          description: Missing URL parameter
        500:
          description: Internal Server Error
  /resolve/{shortURL}:
    get:
      summary: Resolve a short URL
      description: Resolves a short URL to its original long URL and redirects.
      parameters:
        - in: path
          name: shortURL
          required: true
          description: The short URL to be resolved.
          schema:
            type: string
      responses:
        303:
          description: See Other (Redirect)
          headers:
            Location:
              schema:
                type: string
                description: The original long URL.
        404:
          description: Short URL not found
        500:
          description: Internal Server Error
  /delete:
    delete:
      summary: Delete a short URL
      description: Deletes a short URL from the database.
      parameters:
        - in: query
          name: shortURL
          required: true
          description: The short URL to be deleted.
          schema:
            type: string
      responses:
        200:
          description: Short URL deleted successfully
        400:
          description: Missing shortURL parameter
        500:
          description: Internal Server Error
