service: url-shortener

plugins:
  - serverless-go-build
  - serverless-scriptable-plugin

custom:
  script:
    hooks:
      'before:package:createDeploymentArtifacts':
        - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bin/main src/main.go

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  role: arn:aws:iam::312953117411:role/Shortener
  environment:
    BASE_URL: https://me.li

package:
  include:
    - bin/**
  exclude:
    - ./**
    - node_modules/**
    - .serverless/**
    - .git/**


functions:
  urlHandler:
    handler: main
    events:
      - http:
          path: create
          method: post
      - http:
          path: resolve/{shortURL}
          method: get
      - http:
          path: delete
          method: delete
