AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  UrlShortenerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UrlShortener
      AttributeDefinitions:
        - AttributeName: shortUrl
          AttributeType: S
        - AttributeName: longUrl
          AttributeType: S
      KeySchema:
        - AttributeName: shortUrl
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: LongUrlIndex
          KeySchema:
            - AttributeName: longUrl
              KeyType: HASH
          Projection:
            ProjectionType: ALL

Outputs:
  UrlShortenerTableArn:
    Description: "ARN of the UrlShortener Table"
    Value: !GetAtt UrlShortenerTable.Arn
