name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.3

      - name: Compile Go code
        run: go build -v -o bin/main ./src/main.go

      - name: Lint Go code
        run: |
          go get -u golang.org/x/lint/golint
          golint ./src/...