name: Validate

on:
  push:
    branches:
      - testing

jobs:
    validate:
        name: Validate Code
        runs-on: ubuntu-latest
        services:
            localstack:
                image: localstack/localstack
                env:
                    SERVICES: dynamodb
                    DEFAULT_REGION: us-east-1
                ports:
                    - "4566:4566"



    build:
        name: Build and Test
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.21.3

        - name: Build
          run: go build -v ./src

        - name: Run Unit Tests
          run: go test -v ./src

        - name: Run Go Lint
          run: |
            go install golang.org/x/lint/golint@latest
            golint ./src...

        - name: Run Go Vet
          run: go vet ./src...

        - name: Run Go FMT
          run: |
            if [[ -n "$(gofmt -l ./src)" ]]; then
                echo "Go code is not properly formatted:"
                gofmt -d ./src
                exit 1
            fi
